version: 0.2

phases:
  build:
    commands:
      - docker build -t cat-doorbell-model-input-image:latest .
  post_build:
    commands:
      # Navigate to the parent directory of the output directory
      - cd /output
      # Zip the directory
      - zip -r cat-doorbell-model-input.zip cat-doorbell-model-input
      # Move the zip file to a known location for artifacts
      - mv cat-doorbell-model-input.zip /artifacts/
