version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y git curl unzip zip python3 python3-pip wget
      # Install ffmpeg from a separate repository if necessary
      - amazon-linux-extras install -y epel
      - yum install -y ffmpeg
      - pip3 install --quiet --quiet --no-cache-dir -r requirements.txt
      - mkdir /input /output /artifacts
  pre_build:
    commands:
      - wget --quiet http://storage.googleapis.com/us_audioset/youtube_corpus/v1/features/features.tar.gz -O /input/features.tar.gz
      - tar -xzf /input/features.tar.gz -C /input
      - mv /input/audioset_v1_embeddings /input/audioset
      - rm /input/features.tar.gz
  build:
    commands:
      - python3 extract_samples.py
  post_build:
    commands:
      # Navigate to the parent directory of the output directory
      - cd /output
      # Zip the directory
      - zip -r cat-doorbell-model-input.zip cat-doorbell-model-input
      # Move the zip file to a known location for artifacts
      - mv cat-doorbell-model-input.zip /artifacts/
artifacts:
  files:
    - /artifacts/cat-doorbell-v3-model-input.zip # Or cat-doorbell-v3-model-input.tar.gz
  # Specify the S3 bucket name
  name: cat-doorbell-model-input-artifacts
  discard-paths: yes

